version: "3"

tasks:
  install:
    desc: Install dependencies and dev-dependencies
    cmds:
      - python -m pip install --user poetry
      - python -m poetry config virtualenvs.in-project true
      - python -m poetry install --no-root

  format:
    desc: Formats the source code
    cmds:
      - python -m poetry run black hypermesh_lattice_mesher

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - python -m poetry run black --check hypermesh_lattice_mesher
      - python -m poetry run flake8 hypermesh_lattice_mesher --count --select=E9,F63,F7,F82 --show-source --statistics
      - python -m poetry run flake8 hypermesh_lattice_mesher --exclude ./hypermesh_lattice_mesher/data/ --count --max-complexity=10 --max-line-length=127
      - python -m poetry run pylint hypermesh_lattice_mesher --ignore=hypermesh_lattice_mesher/tests

  build:
    desc: Builds the puthon package
    cmds:
      - python -m poetry build

  test:
    desc: Runs the test suite.
    cmds:
      - |
        python -m poetry run pytest \
        --cov-report html:cov_html \
        --cov-report term:skip-covered \
        --cov=hypermesh_lattice_mesher \
        --cov-report=term-missing

  help:
    desc: runs the cli and shows help for the commands
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main --help

  mesh:
    desc: Mesh a 3d file with rod elements with tcl commands. Slow when large
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main mesh {{.CLI_ARGS}}

  meshfemfile:
    desc: Mesh a 3d file with rod elements directly as fem file, no tcl, more speed
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main meshfemfile {{.CLI_ARGS}}

  readdisplacement:
    desc: Reads the total displacement values from an .h3d file and saves a file of those values
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main readdisplacement {{.CLI_ARGS}}
  
  readstress:
    desc: Reads the axial stress values from an .h3d file and saves a file of those values
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main readstress {{.CLI_ARGS}}

  update-material-values:
    desc: Reads the axial stress values from an .h3d file and saves a file of those values
    cmds: 
      - poetry run python -m hypermesh_lattice_mesher.main update-material-values {{.CLI_ARGS}}